# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Isolate (quarantine) endpoints from the network"


class Input:
    AGENT = "agent"
    QUARANTINE_STATE = "quarantine_state"
    WHITELIST = "whitelist"


class Output:
    FAILURES = "failures"
    SUCCESSFUL = "successful"


class QuarantineInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "agent": {
      "type": "array",
      "title": "Agent",
      "description": "Agent to perform quarantine action on. Accepts IP address, MAC address, hostname, UUID or agent ID",
      "items": {
        "type": "string"
      },
      "order": 1
    },
    "quarantine_state": {
      "type": "boolean",
      "title": "Quarantine State",
      "description": "True to quarantine host, false to unquarantine hosts",
      "order": 2
    },
    "whitelist": {
      "type": "array",
      "title": "Whitelist",
      "description": "This list contains a set of devices that should not be blocked. This can include IPs, hostnames, UUIDs and agent IDs",
      "items": {
        "type": "string"
      },
      "order": 3
    }
  },
  "required": [
    "agent",
    "quarantine_state"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class QuarantineOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "failures": {
      "type": "array",
      "title": "Failure",
      "description": "List of hosts on which the operation attempt was unsuccessful",
      "items": {
        "$ref": "#/definitions/quarantine_failures"
      },
      "order": 2
    },
    "successful": {
      "type": "array",
      "title": "Successful",
      "description": "List of hosts on which the operation was successfully attempted (Note this does not guarantee that the operation itself was successful, only that the API call was able to be successfully performed)",
      "items": {
        "type": "string"
      },
      "order": 1
    }
  },
  "required": [
    "failures"
  ],
  "definitions": {
    "quarantine_failures": {
      "type": "object",
      "title": "quarantine_failures",
      "properties": {
        "input_key": {
          "type": "string",
          "title": "Input Key",
          "description": "The input key name",
          "order": 1
        },
        "error": {
          "type": "string",
          "title": "Error",
          "description": "The message describing why the operation has failed",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)